export const FILTER_SELECT_ONCHANGE_1 = "FILTER_SELECT_ONCHANGE_1"
export const FILTER_SELECT_ONCHANGE_2 = "FILTER_SELECT_ONCHANGE_2"
export const FILTER_SELECT_ONCHANGE_3 = "FILTER_SELECT_ONCHANGE_3"



